export const Hero = () => {
  return (
      <div className="py-10 bg-muted">
        <h1 className="text-3xl font-bold">Create Next App</h1>
        <p className="text-muted">Generated by create next app</p>
      </div>
  )
}